export const EMAIL_INPUT_BY_TYPE = '[type="email"]'
export const PASSWORD_INPUT_BY_TYPE = '[type="password"]'
export const REMEMBER_CHECKBOX_BY_ID = '#rememberchb'
export const LOGIN_BUTTON_BY_TYPE = '[type="submit"]'
export const FEEDBACK_ERROR_BY_TEXT = 'Preencha este campo'