name: test-login-mobile

on: [push, pull_request]

jobs:
  test-login-mobile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm i
    - run: npm run test:LoginMobile